export enum AddressType {
  PERSONAL_ADDRESS = 'PERSONAL_ADDRESS',
  DELIVERY_ADDRESS = 'DELIVERY_ADDRESS',
  BILLING_ADDRESS = 'BILLING_ADDRESS',
  DELIVERY_AND_BILLING_ADDRESS = 'DELIVERY_AND_BILLING_ADDRESS',
}
