export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FAILED_PAYMENT = 'FAILED_PAYMENT',
  PAID = 'PAID',
  SENT = 'SENT',
  ON_DELIVERY = 'ON_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
